services:

  postgres:
    image: postgres:16
    container_name: movie-watchlist-postgres

    environment:
      POSTGRES_DB: movie_watchlist
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password

    ports:
      - "5432:5432"

    volumes:
      - movie_watchlist_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U movie_user -d movie_watchlist"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  movie_watchlist_postgres_data: