spring:
  application:
    name: watchlist

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_watchlist
    username: movie_user
    password: movie_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true