spring:
  application:
    name: watchlist

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_watchlist
    username: movie_user
    password: movie_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      #Do not create or modify my database schema. Just verify that the schema matches the entity mappings.

  flyway:
    enabled: true